import { parseNMEtoPhaser } from './src/shaderConverter.js';
import fs from 'fs';

const jsCode = `var nodeMaterial = new BABYLON.NodeMaterial("Headlamp_Mask_Wireframe");
nodeMaterial.mode = BABYLON.NodeMaterialModes.Material;
var position = new BABYLON.InputBlock("position");
position.visibleInInspector = false;
position.visibleOnFrame = false;
position.target = 1;
position.setAsAttribute("position");
var WorldPos = new BABYLON.TransformBlock("WorldPos");
WorldPos.visibleInInspector = false;
WorldPos.visibleOnFrame = false;
WorldPos.target = 1;
WorldPos.complementZ = 0;
WorldPos.complementW = 1;
var World = new BABYLON.InputBlock("World");
World.visibleInInspector = false;
World.visibleOnFrame = false;
World.target = 1;
World.setAsSystemValue(BABYLON.NodeMaterialSystemValues.World);
var WorldPosViewProjectionTransform = new BABYLON.TransformBlock("WorldPos * ViewProjectionTransform");
WorldPosViewProjectionTransform.visibleInInspector = false;
WorldPosViewProjectionTransform.visibleOnFrame = false;
WorldPosViewProjectionTransform.target = 1;
WorldPosViewProjectionTransform.complementZ = 0;
WorldPosViewProjectionTransform.complementW = 1;
var ViewProjection = new BABYLON.InputBlock("ViewProjection");
ViewProjection.visibleInInspector = false;
ViewProjection.visibleOnFrame = false;
ViewProjection.target = 1;
ViewProjection.setAsSystemValue(BABYLON.NodeMaterialSystemValues.ViewProjection);
var VertexOutput = new BABYLON.VertexOutputBlock("VertexOutput");
VertexOutput.visibleInInspector = false;
VertexOutput.visibleOnFrame = false;
VertexOutput.target = 1;
var uv = new BABYLON.InputBlock("uv");
uv.visibleInInspector = false;
uv.visibleOnFrame = false;
uv.target = 1;
uv.setAsAttribute("uv");
var VectorSplitter = new BABYLON.VectorSplitterBlock("VectorSplitter");
VectorSplitter.visibleInInspector = false;
VectorSplitter.visibleOnFrame = false;
VectorSplitter.target = 4;
var Multiply = new BABYLON.MultiplyBlock("Multiply");
Multiply.visibleInInspector = false;
Multiply.visibleOnFrame = false;
Multiply.target = 4;
var Speed = new BABYLON.InputBlock("Speed");
Speed.visibleInInspector = false;
Speed.visibleOnFrame = false;
Speed.target = 1;
Speed.value = 0.5;
Speed.min = 0;
Speed.max = 0;
Speed.isBoolean = false;
Speed.matrixMode = 0;
Speed.animationType = BABYLON.AnimatedInputBlockTypes.None;
Speed.isConstant = false;
var Subtract = new BABYLON.SubtractBlock("Subtract");
Subtract.visibleInInspector = false;
Subtract.visibleOnFrame = false;
Subtract.target = 4;
var Time = new BABYLON.InputBlock("Time");
Time.visibleInInspector = false;
Time.visibleOnFrame = true;
Time.target = 1;
Time.value = 1596.1087200003203;
Time.min = 0;
Time.max = 0;
Time.isBoolean = false;
Time.matrixMode = 0;
Time.animationType = BABYLON.AnimatedInputBlockTypes.Time;
Time.isConstant = false;
var VectorMerger = new BABYLON.VectorMergerBlock("VectorMerger");
VectorMerger.visibleInInspector = false;
VectorMerger.visibleOnFrame = false;
VectorMerger.target = 4;
VectorMerger.xSwizzle = "x";
VectorMerger.ySwizzle = "y";
VectorMerger.zSwizzle = "z";
VectorMerger.wSwizzle = "w";
var Texture = new BABYLON.TextureBlock("Texture");
Texture.visibleInInspector = false;
Texture.visibleOnFrame = false;
Texture.target = 3;
Texture.convertToGammaSpace = false;
Texture.convertToLinearSpace = false;
Texture.disableLevelMultiplication = false;
var ImageSourceBlock = new BABYLON.ImageSourceBlock("ImageSourceBlock");
ImageSourceBlock.visibleInInspector = false;
ImageSourceBlock.visibleOnFrame = false;
ImageSourceBlock.target = 3;
var FragmentOutput = new BABYLON.FragmentOutputBlock("FragmentOutput");
FragmentOutput.visibleInInspector = false;
FragmentOutput.visibleOnFrame = false;
FragmentOutput.target = 2;
FragmentOutput.convertToGammaSpace = false;
FragmentOutput.convertToLinearSpace = false;
FragmentOutput.useLogarithmicDepth = false;
var Divide = new BABYLON.DivideBlock("Divide");
Divide.visibleInInspector = false;
Divide.visibleOnFrame = false;
Divide.target = 4;
var Float = new BABYLON.InputBlock("Float");
Float.visibleInInspector = false;
Float.visibleOnFrame = false;
Float.target = 1;
Float.value = 5;
Float.min = 0;
Float.max = 0;
Float.isBoolean = false;
Float.matrixMode = 0;
Float.animationType = BABYLON.AnimatedInputBlockTypes.None;
Float.isConstant = false;
position.output.connectTo(WorldPos.vector);
World.output.connectTo(WorldPos.transform);
WorldPos.output.connectTo(WorldPosViewProjectionTransform.vector);
ViewProjection.output.connectTo(WorldPosViewProjectionTransform.transform);
WorldPosViewProjectionTransform.output.connectTo(VertexOutput.vector);
uv.output.connectTo(VectorSplitter.xyIn);
VectorSplitter.x.connectTo(Multiply.left);
Speed.output.connectTo(Multiply.right);
Multiply.output.connectTo(Subtract.left);
Time.output.connectTo(Subtract.right);
Subtract.output.connectTo(VectorMerger.x);
VectorSplitter.y.connectTo(VectorMerger.y);
VectorMerger.xy.connectTo(Texture.uv);
ImageSourceBlock.source.connectTo(Texture.source);
Texture.rgb.connectTo(FragmentOutput.rgb);
Texture.a.connectTo(FragmentOutput.a);
Texture.rgb.connectTo(FragmentOutput.glow);
nodeMaterial.addOutputNode(VertexOutput);
nodeMaterial.addOutputNode(FragmentOutput);
nodeMaterial.build();`;

try {
    const result = parseNMEtoPhaser(jsCode);
    console.log('=== GENERATED GLSL ===');
    console.log(result.glsl);
    console.log('\n=== CONFIG ===');
    console.log('uniforms:', result.uniforms);
    console.log('samplers:', result.samplers);
    console.log('defaultValues:', result.defaultValues);
    console.log('hasAlpha:', result.hasAlpha);
} catch (err) {
    console.error('ERROR:', err.message, err.stack);
}
